blank_issues_enabled: false
contact_links:
  - name: LinkedIn
    url: https://www.linkedin.com/in/hadryan-fortinis-9b990538a
    about: Para contato profissional, fale comigo pelo LinkedIn.
  - name: Email
    url: mailto:hadryanfortinis89@gmail.com
    about: Prefere email? Escreva para hadryanfortinis89@gmail.com.
